language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t uday3110/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true uday3110/react-test npm test

after_success:
  - docker build -t uday3110/multi-client ./client
  - docker build -t uday3110/multi-nginx ./nginx
  - docker build -t uday3110/multi-server ./server
  - docker build -t uday3110/multi-worker ./worker
  # Login into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to docker hub
  - docker push uday3110/multi-client
  - docker push uday3110/multi-nginx
  - docker push uday3110/multi-server
  - docker push uday3110/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env-1
  bucket: elasticbeanstalk-us-west-1-xxxxx
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

